server:
  host: 127.0.0.1
  port: 8080
  multipartBuffSizeBytes: 0xFFFF
mongo:
  url: mongodb://localhost:27017
  db: local
  collection:
    - mock
  caFile:
  certFile:
  keyFile:
log:
  encoding: json
  level: Info
  output:
    - stdout
    - /tmp/logs
  erroutput:
    - stderr